//VARIABLES FOR GHOST CAT 
WALKING_ANIM_NAME = sGhostCat_Walking
IDLE_ANIM_NAME = sGhostCat_Idle
FALLING_ANIM_NAME = sGhostCat_Falling
JUMPING_ANIM_NAME = sGhostCat_Jumping
ORIGINAL_SCALE_SIZE = 0.7

SPEED = 1
GRAVITY = 0.05
JUMP_SPEED = 2.2
JUMP_NUMBER = 1
GROUND_THRESHOLD = 0.15

O_COLLIDABLES_PARENT = oGhostCat_ParentWalls
O_COLLIDABLE_WALL = oGhostWall
O_COLLIDABLE_SLOPE = oGhostWall_Slope


//VARIABLES THAT WILL CHANGE IN RUN TIME FOR GHOST CAT 
xVel = 0
yVel = 0
jumpsLeft = JUMP_NUMBER
isOnGround = true;

slopeMax = 4
