// VALUES FOR LIVING CAT

WALKING_ANIM_NAME = sLivingCat_Walking
IDLE_ANIM_NAME = sLivingCat_Idle
FALLING_ANIM_NAME = sLivingCat_Falling
JUMPING_ANIM_NAME = sLivingCat_Jumping
ORIGINAL_SCALE_SIZE = 0.7

SPEED = 1
GRAVITY = 0.1
JUMP_SPEED = 2.8
JUMP_NUMBER = 1
GROUND_THRESHOLD = 0.1
PUSH_STRENGTH = 1;

O_COLLIDABLES_PARENT = oLivingCat_ParentWalls
O_COLLIDABLE_WALL = oLivingWall
O_COLLIDABLE_SLOPE = oLivingWall_Slope
O_BOX = oBox



//VARIABLES THAT WILL CHANGE IN RUN TIME FOR LIVING CAT 
xVel = 0
yVel = 0
jumpsLeft = JUMP_NUMBER
isOnGround = true;

slopeMax = 4
